### ISSUE TITLE
add ssl

### ISSUE THREAD

**Issue by blainekasten** [NebraskaJS/nebraskajs.com#15]
service worker won't really work until we add ssl. What's the overhead to do this?

**Comment by mattdsteele** [comment]
I'm not an expert in this, but I had local hero @jmhobbs give me the rundown a few weeks ago on what getting a cert entails. What follows is his email:

So, here's the low-down on the SSL cert.   It's a five step process.

1. Generate your private key
2. Generate a CSR, Certificate Signing Request
3. Submit the CSR to your CA and wait
4. Respond to their verification email
5. Install the certificate they send back to you

I usually go with a Comodo DV certificate, because I'm cheap, it's secure, and I don't really believe "customers" know there is a difference between DV/OV/EV or would trust me more either way.  It's faster to issue too.  I get mine from Namecheap, because I do my domain registration there already anyway.

Pretty much everybody uses openssl to generate their key and CSR.  You can do it in one command even, that's how common it is.  Here's a terminal recording of the process.  It just asks you some questions and you answer them.

https://dl.dropboxusercontent.com/u/28665584/ssl-recording.html

You'll note I use "rsa:2048" in there.  That can change between registrars, they will tell you what they accept.  Comodo takes a 2048 bit key, or larger.

Also, make sure you are exact about the FQDN when you generate the CSR.  Whatever domain you use there is the only domain the certificate will be valid for.  In that terminal recording I generated it with www.nejsconf.com, but we are currently using the bare domain, so that CSR is wrong.  If you need to check an existing CSR to make sure it is right, you can use openssl for that too:

(env)jmhobbs@venera:~/ssl ✪ openssl req -text -noout -verify -in nejsconf.csr | head -n 10
verify OK
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: C=US, ST=Nebraska, L=Omaha, O=Nebraska JavaScript LLC, CN=www.nejsconf.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:a8:ef:6d:af:c6:ad:a9:3a:2c:47:31:c8:83:95:
                    f2:22:7b:24:72:a7:7d:4f:b9:bc:5e:c4:68:fb:cb:
(env)jmhobbs@venera:~/ssl ✪

Once you've got it ready, you pay online and upload your CSR.  For a DV certificate they will email an admin address on the domain, usually based on the WHOIS.  They may also do verification through a TXT DNS record or something, depends on the CA.

After you've confirmed the domain they mail you a certificate.  Installation depends on your server YMMV.  For installation, best suggestion is install it, then check it with something like https://www.ssllabs.com/ssltes/ and make adjustments to your cipher suite based on their grade.  Here's Pack's API cert - https://www.ssllabs.com/ssltest/analyze.html?d=api.packdog.com&s=184.73.198.73

There is other stuff to do too, like HSTS, but that is all either server config, or done in code.

**Comment by snekse** [comment]
If we don't have real high consumer driven trust needs, http://startssl.com
has a free option. It's a common starting point until you have the need for
bigger and better. It has to be done once a year though.

**Comment by jmhobbs** [comment]
StartSSL gives me the heebie jeebies.  I don't have a reason, they just do.  I think it's the bad website.

That said, I'm never opposed to free :)

**Comment by jerodsanto** [comment]
I've had bad experiences w/ StartSSL as well. My $.02 is we buck up and buy one this year then maybe switch to [Let's Encrypt](https://letsencrypt.org) later. Or we could just wait until "Mid-2015" if it's not a pressing issue (which it isn't for a site like this, imo).

**Comment by snekse** [comment]
I'm pretty sure we could pass the virtual hat around and gather enough to get us by for a year.  I would think you'd want one in place before NEJS Conf.  It seems like letsencrypt.org would be up and running by then.  Waiting seems like a good choice.

**Comment by jmhobbs** [comment]
Nice guide from EFF on A+ support - https://www.eff.org/deeplinks/2015/04/effs-updated-ssl-configuration

**Comment by jmhobbs** [comment]
Lets Encrypt is in public beta now - https://letsencrypt.org/2015/12/03/entering-public-beta.html

**Comment by mattdsteele** [comment]
@jmhobbs yeah buddy!

Where's this site actually hosted? I threw it up on my personal site (S3 + Cloudfront) and it was a bit of a pain due to it not being one of their supported environments. Plus their 90 day expiration period encourages automation. But if it's Apache or Nginx, and we have root on the box, this is a no-brainer to do now.

**Comment by jmhobbs** [comment]
It's on Nearly Free Speech, so we don't have root.  And it looks like it's all done through support tickets, so the 90 day window is probably an issue.  Maybe best to keep waiting.

**Comment by mattdsteele** [comment]
Looks like they're gonna automate it for everything, but they'll be in "the second wave of adopters". https://members.nearlyfreespeech.net/forums/viewtopic.php?p=41843#41843

**Comment by zachleat** [comment]
I’m open to switching hosts!

**Comment by zachleat** [comment]
Any recommendations?

**Comment by mattdsteele** [comment]
I'll let others comment but unless you want to manage a full VPS from DigitalOcean or something, it's probably best just to stay on NFSN. I'm not aware of other "drop your static files here" hosts that have Let's Encrypt fully automated yet, though they're all probably gonna work through it in the next few months.

**Comment by nicknisi** [comment]
I have a linode box sitting around doing next to nothing.

**Comment by zachleat** [comment]
@jmhobbs what provider did you use to get your cert for nejsconf?

**Comment by jmhobbs** [comment]
I think it's a Comodo from Namecheap.

On Wednesday, December 23, 2015, Zach Leatherman <notifications@github.com>
wrote:

> @jmhobbs <https://github.com/jmhobbs> what provider did you use to get
> your cert for nejsconf?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NebraskaJS/nebraskajs.com/issues/15#issuecomment-167034357>
> .
>


-- 
- John Hobbs

john@velvetcache.org

http://www.velvetcache.org/

**Comment by zachleat** [comment]
Closed per NSFN now including an awesome letsencrypt workflow with the `tls-setup.sh` script
